TOP = ../..
include $(TOP)/configure/CONFIG

SCRIPTS+=stasubtest-mk-IOC-linux.boot
SCRIPTS+=stasubtest-mk-sim2.boot
SCRIPTS+=stasubtest-mk-sim3.boot
SCRIPTS+=stasubtest-mk-sim4.boot
SCRIPTS+=stasubtest-mk-tcs.boot
SCRIPTS+=stasubtest-mk-mcs.boot

include $(TOP)/configure/RULES
